### ISSUE TITLE
Getting /bin/sh: 1: ffmpeg-length: not found

### ISSUE THREAD

**Issue by jayavanth** [andrewowens/multisensory#1]
when I run `python sep_video.py ../data/translator.mp4 --model full --duration_mult 4 --out ../results/
`. Is it an alias for something?

**Comment by andrewowens** [comment]
Sorry about that! I pushed a fix. Any luck now?

**Comment by jayavanth** [comment]
Yep. That fixed it. Also, I think CUDA 9.0+ should be a dependency
