### ISSUE TITLE
Issue on Large Videos

### ISSUE THREAD

**Issue by ChaitanyaBoggavarapu** [andrewowens/multisensory#32]
Thanks for great paper. When working with large videos the maximum duration of separation is 4min. Can this applied to whole video for separation at once

**Comment by andrewowens** [comment]
You can try setting the `--duration_mult` flag, e.g. `--duration_mult 4` will use a video of 4x the default duration. 

However, 4 minutes might be too much to fit in memory. In that case, you could try splitting the video into parts, separating them independently, and merging them together. There is an (undocumented) command line argument for doing this. Set the `--duration` flag with the length that you'd like (e.g. `--duration 20` for a 20-second video). I've never tried it on a video that long, though.

**Comment by ChaitanyaBoggavarapu** [comment]
Thanks for your reply. I will try doing by splitting and merging
