### ISSUE TITLE
TypeError: convolution() got multiple values for argument 'weights_regularizer'

### ISSUE THREAD

**Issue by chouqin3** [andrewowens/multisensory#7]
I got error like this, what happened, please help me to fix.
Traceback (most recent call last):
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 398, in <module>
    ret = run(arg.vid_file, t, arg.clip_dur, pr, gpus[0], mask = arg.mask, arg = arg, net = net)
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 294, in run
    net.init()
  File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 42, in init
    pr, reuse = False, train = False)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\sourcesep.py", line 953, in make_net
    vid_net_full = shift_net.make_net(ims, sfs, pr, None, reuse, train)
  File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\shift_net.py", line 419, in make_net
    sf_net = conv2d(sf_net,num_outputs= 64, kernel_size= [65, 1], scope = 'sf/conv1_1', stride = [4, 1], padding='SAME', reuse = reuse) # by lg 8.20
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
TypeError: convolution() got multiple values for argument 'weights_regularizer'

**Comment by andrewowens** [comment]
Try installing TensorFlow 1.8, e.g. with "pip install tensorflow-gpu==1.8". This code broke in newer versions of TensorFlow.

**Comment by andrewowens** [comment]
This might be a Windows compatibility issue. Try decreasing the number in the line: "pool.map_async(f, xs).get(10000000)" in util.py -- say, to 100000.

**Comment by chouqin3** [comment]
**Thank you for your response again. It's really the problem of compatibility.**

**Comment by andrewowens** [comment]
I've now (hopefully) fixed both of these compatibility issues. Please let me know if you still have problems.

**Comment by chouqin3** [comment]
> I got error like this, what happened, please help me to fix.
> Traceback (most recent call last):
> File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 398, in 
> ret = run(arg.vid_file, t, arg.clip_dur, pr, gpus[0], mask = arg.mask, arg = arg, net = net)
> File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 294, in run
> net.init()
> File "D:/Workspace/PythonProjects/studyProjects/multisensory/src/sep_video.py", line 42, in init
> pr, reuse = False, train = False)
> File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\sourcesep.py", line 953, in make_net
> vid_net_full = shift_net.make_net(ims, sfs, pr, None, reuse, train)
> File "D:\Workspace\PythonProjects\studyProjects\multisensory\src\shift_net.py", line 419, in make_net
> sf_net = conv2d(sf_net,num_outputs= 64, kernel_size= [65, 1], scope = 'sf/conv1_1', stride = [4, 1], padding='SAME', reuse = reuse) # by lg 8.20
> File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
> return func(*args, **current_args)
> File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
> conv_dims=2)
> File "C:\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
> return func(*args, **current_args)
> TypeError: convolution() got multiple values for argument 'weights_regularizer'
